### ISSUE TITLE
Question: How do I get user's role?

### ISSUE THREAD

**Issue by Tatsuki-I** [discord-haskell/discord-haskell#44]
I want to get role of a user who sent a message.
Is this function defined?

**Comment by aquarial** [comment]
Not really. A `User` doesn;t have any roles on it;s own because `Role`s come from `Guild`s. A DM for example, won;t have any roles with the User. A `GuildMember` is an object that pairs a `Guild` with a `User`. 

So the question is, given a `Message` with `User` and `Maybe GuildId`, how to get a `GuildMember`. 

Sending a `R.GetGuildMember :: GuildId -> UserId -> R.GuildRequest GuildMember` for every message would work, but is inefficient.

Caching would be better, but it's complicated. would be nice if I completed `Cache`. Ugh. I;m not really interested in doing a bunch of work on this.

**Comment by social-anthrax** [comment]
@Tatsuki-I as aquarial said, doing so is inefficient, however, should work ok on bots who don't get too much traffic. Here is an example of how one could return a list of Roles a user has:
```hs
getUserRoles :: UserId -> GuildId -> DiscordHandler [Role]
getUserRoles i g = do
    Right allRoles <- restCall $ R.GetGuildRoles g
    Right userG <- restCall $ R.GetGuildMember g i
    let filtered = filter (\x -> roleId x `elem` memberRoles userG) allRoles
    return filtered
```

**Comment by L0neGamer** [comment]
Closing issue as this can be implemented using existing functions, or is part of developing the cache.
